# Generated by Django 3.1.6 on 2021-03-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unnamed', max_length=64),
        ),
    ]
