# Generated by Django 3.1.6 on 2021-03-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
