# Generated by Django 3.1.6 on 2021-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unnamed', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='project_name',
            field=models.CharField(default='Untitled', max_length=10),
        ),
    ]
