# Generated by Django 3.1.6 on 2021-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0007_auto_20210324_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='teamApp.Profile'),
        ),
    ]
